# Generated by Django 4.2.13 on 2024-07-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_video_description_video_github_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
    ]
